//------------------------------------------------------------------------------ 
// <auto-generated>
// This code was generated by a tool. 
// 
// Changes to this will be lost if the code is regenerated.
// #region ranges will be protected
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace CORE.Site
{
}